substitutions:
  hostname: "switch10"
  device_description: Bedroom Lamp

esphome:
  name: ${hostname}
  comment: ${device_description}

esp8266:
  board: esp01_1m
  framework:
    version: latest

packages:
  wifi: !include common/wifi.yaml
  api: !include common/api.yaml
  logger: !include common/logger.yaml
  ota: !include common/ota.yaml

# web_server:
#   port: 80

status_led:
  pin:
    number: GPIO13
    inverted: true

sensor:
  - <<: !include common/uptime.yaml
#  - <<: !include common/signal.yaml

text_sensor:
  - <<: !include common/version.yaml

binary_sensor:
  - <<: !include common/status.yaml
  - platform: gpio
    pin: GPIO04
    name: "$hostname Reset Button"
    id: reset
    internal: true
    filters:
      - invert:
      - delayed_off: 10ms
    on_press:
      - switch.toggle:
          id: relay
  - platform: gpio
    name: "$hostname Button"
    pin: GPIO00
    filters:
      - invert:
      - delayed_off: 10ms
    on_press:
      - switch.toggle:
          id: relay

switch:
  - <<: !include common/restart.yaml
  - platform: gpio
    name: "$hostname Switch"
    icon: "mdi:lightbulb_outline"
    pin: GPIO12
    id: relay
    restore_mode: restore_default_off